"""create persistence schema

Revision ID: 1f57c04b8013
Revises:
Create Date: 2026-08-28 00:31:02.011461

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1f57c04b8013"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("canonical_name", sa.String(length=500), nullable=False),
        sa.Column("normalized_name", sa.String(length=500), nullable=False),
        sa.Column("uei", sa.String(length=32), nullable=True),
        sa.Column(
            "organization_type", sa.String(length=32), server_default="unknown", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_companies")),
        sa.UniqueConstraint("normalized_name", name=op.f("uq_companies_normalized_name")),
        sa.UniqueConstraint("uei", name=op.f("uq_companies_uei")),
    )
    op.create_table(
        "ingestion_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), server_default="running", nullable=False),
        sa.Column("requested_start_date", sa.Date(), nullable=False),
        sa.Column("requested_end_date", sa.Date(), nullable=False),
        sa.Column("fetched_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("relevant_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("stored_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("duplicate_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "fetched_count >= 0 AND relevant_count >= 0 AND stored_count >= 0 AND duplicate_count >= 0",
            name=op.f("ck_ingestion_runs_counts_nonnegative"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_runs")),
    )
    op.create_index(
        "ix_ingestion_runs_source_started_at",
        "ingestion_runs",
        ["source", "started_at"],
        unique=False,
    )
    op.create_table(
        "awards",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("company_id", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("source_award_id", sa.String(length=256), nullable=False),
        sa.Column("generated_internal_id", sa.String(length=512), nullable=True),
        sa.Column("recipient_name", sa.String(length=500), nullable=False),
        sa.Column("recipient_uei", sa.String(length=32), nullable=True),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("awarding_agency", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("award_start_date", sa.Date(), nullable=True),
        sa.Column("award_end_date", sa.Date(), nullable=True),
        sa.Column("naics_code", sa.String(length=16), nullable=True),
        sa.Column("psc_code", sa.String(length=16), nullable=True),
        sa.Column("evidence_url", sa.Text(), nullable=False),
        sa.Column(
            "detected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("amount >= 0", name=op.f("ck_awards_amount_nonnegative")),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_awards_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_awards")),
        sa.UniqueConstraint("source", "source_award_id", name=op.f("uq_awards_source")),
    )
    op.create_index(
        "ix_awards_company_start_date", "awards", ["company_id", "award_start_date"], unique=False
    )
    op.create_table(
        "company_aliases",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("company_id", sa.String(length=64), nullable=False),
        sa.Column("alias", sa.String(length=500), nullable=False),
        sa.Column("normalized_alias", sa.String(length=500), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_company_aliases_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_company_aliases")),
        sa.UniqueConstraint(
            "company_id", "normalized_alias", "source", name=op.f("uq_company_aliases_company_id")
        ),
    )
    op.create_index(
        "ix_company_aliases_normalized_alias", "company_aliases", ["normalized_alias"], unique=False
    )
    op.create_table(
        "signals",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("company_id", sa.String(length=64), nullable=False),
        sa.Column("award_id", sa.String(length=64), nullable=False),
        sa.Column(
            "signal_type", sa.String(length=64), server_default="government_award", nullable=False
        ),
        sa.Column("relevance_score", sa.Integer(), nullable=False),
        sa.Column("matched_terms", sa.JSON(), nullable=False),
        sa.Column("reasons", sa.JSON(), nullable=False),
        sa.Column("organization_type", sa.String(length=32), nullable=False),
        sa.Column("is_startup_candidate", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("quality_flags", sa.JSON(), nullable=False),
        sa.Column(
            "detected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "relevance_score BETWEEN 0 AND 100", name=op.f("ck_signals_relevance_score_range")
        ),
        sa.ForeignKeyConstraint(
            ["award_id"], ["awards.id"], name=op.f("fk_signals_award_id_awards"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_signals_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_signals")),
        sa.UniqueConstraint("award_id", name=op.f("uq_signals_award_id")),
    )
    op.create_index(
        "ix_signals_startup_score",
        "signals",
        ["is_startup_candidate", "relevance_score"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_signals_startup_score", table_name="signals")
    op.drop_table("signals")
    op.drop_index("ix_company_aliases_normalized_alias", table_name="company_aliases")
    op.drop_table("company_aliases")
    op.drop_index("ix_awards_company_start_date", table_name="awards")
    op.drop_table("awards")
    op.drop_index("ix_ingestion_runs_source_started_at", table_name="ingestion_runs")
    op.drop_table("ingestion_runs")
    op.drop_table("companies")
    # ### end Alembic commands ###
