"""add signal priority scoring

Revision ID: 6f520f8eed69
Revises: 7a9875d23d33
Create Date: 2026-09-15 23:38:35.629952

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6f520f8eed69"
down_revision: str | Sequence[str] | None = "7a9875d23d33"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "signals", sa.Column("priority_score", sa.Integer(), server_default="0", nullable=False)
    )
    op.add_column(
        "signals", sa.Column("priority_reasons", sa.JSON(), server_default="[]", nullable=False)
    )
    op.create_index("ix_signals_priority_score", "signals", ["priority_score"], unique=False)
    op.create_check_constraint(
        op.f("ck_signals_priority_score_range"), "signals", "priority_score BETWEEN 0 AND 100"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_signals_priority_score_range"), "signals", type_="check")
    op.drop_index("ix_signals_priority_score", table_name="signals")
    op.drop_column("signals", "priority_reasons")
    op.drop_column("signals", "priority_score")
    # ### end Alembic commands ###
