"""add award action date

Revision ID: 7a9875d23d33
Revises: 1f57c04b8013
Create Date: 2026-09-02 05:59:45.487376

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7a9875d23d33"
down_revision: str | Sequence[str] | None = "1f57c04b8013"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("awards", sa.Column("action_date", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("awards", "action_date")
    # ### end Alembic commands ###
